### PR TITLE
Merge pull request #1 from vandernorth/master

### PR DESCRIPTION
**Pull request by tmathura**
# Please Note (you may remove this section before opening your PR):

We receive lots of pull requests, please help us be able to review them by following the below guidelines:
1. If you are adding configuration settings, please be sure to document their usage in your description so they can be added to the wiki.
2. Make sure your code is clean and well-formed. Use comments if necessary to explain why you did something.
3. Make sure your changes are only for a specific purpose. Do not mix several changes into one pull request.
4. If the code is based off another individuals work, be sure to credit them appropriately.
## Fixes (provide links to github issues if you can):

Added reference to noxxDev fork

### CODE REVIEW

**Comment by tmathura** [comment]
please remove these, if possible delete them, thanks. Noob mistake

**Comment by tmathura** [comment]
Thanks! If you have a moment, how do I pull your latest changes into my fork? I am new to github...

**Comment by vandernorth** [comment]
Hope this helps: https://help.github.com/articles/syncing-a-fork/

**Comment by tmathura** [comment]
Thanks.

**Pull request closed without merging**
